# Generated by Django 5.1 on 2026-03-13 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Llm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(default="n/a", max_length=32)),
                ("interaction_name", models.CharField(max_length=64)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("anthropic", "Anthropic"),
                            ("openai", "OpenAI"),
                            ("google", "Google"),
                        ],
                        default="anthropic",
                        max_length=32,
                    ),
                ),
                ("context_windows", models.IntegerField()),
                ("max_output_tokens", models.IntegerField()),
                ("supports_streaming", models.BooleanField(default=False)),
                ("supports_json_output", models.BooleanField(default=False)),
                ("input_cost_per_million_tokens", models.IntegerField()),
                ("output_cost_per_million_tokens", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system", models.TextField(default="", null=True)),
                ("content", models.TextField(default="Hello")),
            ],
        ),
        migrations.CreateModel(
            name="LlmParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=16)),
                ("interaction_name", models.CharField(max_length=16)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("str", "intvalue"),
                            ("float", "floatvalue"),
                            ("int", "strvalue"),
                        ],
                        default="str",
                        max_length=8,
                    ),
                ),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "llm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prompt_tweaker.llm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageParameterLlm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intvalue", models.IntegerField(blank=True, default=None, null=True)),
                ("floatvalue", models.FloatField(blank=True, default=None, null=True)),
                (
                    "strvalue",
                    models.CharField(
                        blank=True, default=None, max_length=256, null=True
                    ),
                ),
                (
                    "llmparameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prompt_tweaker.llmparameter",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prompt_tweaker.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prompt_tweaker.profile",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="prompt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="prompt_tweaker.prompt"
            ),
        ),
    ]
